### ISSUE TITLE
(RFC) Support for multiple profiles 

### ISSUE THREAD

**Issue by hpolloni** [hpolloni/rdsline#15]
Because we only support a single "profile" per file, handling multiple profiles means handling multiple files, which cause pain. We should support multiple profiles.

I'm thinking adding a `profiles` section in the current configuration format. 
```yaml
type: rds-secretsmanager
cluster_arn: arn:aws:rds:us-east-1:<ACCOUNT_ID>:cluster:<CLUSTER_NAME>
secret_arn: arn:aws:secretsmanager:us-east-1:<ACCOUNT_ID>:secret:<SECRET_ID>
database: DATABASE_NAME
credentials:
  profile: default
## This is new
profiles:
  name: otherdb
  type: rds-secretsmanager
  cluster_arn: arn:aws:rds:us-east-1:<ACCOUNT_ID>:cluster:<SOME_OTHER_CLUSTER>
  secret_arn: arn:aws:secretsmanager:us-east-1:<ACCOUNT_ID>:secret:<SECRET_ID>
  database: DATABASE_NAME
  credentials:
    profile: otherdb
```
Then a user can simply do: `rdsline --profile otherdb` or `.profile otherdb` inside the REPL. If no profile is specified, then the top-level profile is used.

The benefit of this approach is that it's backward compatible to the current file format. OTOH, I don't particularly like forcing users to write YAML, so we might need some better UX for writing those profiles.
